backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: "https://jamm.matter.design"
logo_url: "/images/logo.png" # Update this if you have a logo

locale: "en"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/pages"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "src/products"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "config"
    label: "Site Navigation & Footer"
    files:
      - file: "src/config.json"
        label: "Navigation & Footer"
        name: "navigation_footer"
        fields:
          - { label: "Header Links", name: "headerLinks", widget: "list", fields: [
                { label: "Label", name: "menuLabel", widget: "string" },
                { label: "URL", name: "menuLink", widget: "string" }
            ]
          }
          - { label: "Footer Links", name: "footerLinks", widget: "list", fields: [
                { label: "Column Label", name: "subTitle", widget: "string" },
                { label: "Links", name: "links", widget: "list", fields: [
                    { label: "Text", name: "text", widget: "string" },
                    { label: "URL", name: "link", widget: "string" }
                ]}
            ]
          }

  # Add more collections as needed for blog, settings, etc.

# Optional: inject your CSS to match the theme (Decap CMS supports custom styles)
editor:
  preview: false
  styles:
    - "/components/Layout/Globals.css"
